#cloud-config

package_update: false
package_upgrade: false
packages:
  - curl
  - unzip
  - docker.io

write_files:
  - path: /etc/nomad.d/nomad.hcl
    permissions: 0o655
    content: |
      datacenter = "${nomad_datacenter}"
      data_dir   = "/var/lib/nomad"

      server {
        enabled          = ${ nomad_server ? true : false }
        bootstrap_expect = ${ nomad_server_count }

        server_join {
          retry_join = ["provider=gce project_name=${ gcp_project } tag_value=${ nomad_server_tag }"]
        }
      }

      client {
        enabled = ${ nomad_client ? true : false }

        server_join {
          retry_join = ["provider=gce project_name=${ gcp_project } tag_value=${ nomad_server_tag }"]
        }
      }

      ui {
        enabled = true
      }

  - path: /etc/systemd/system/nomad.service
    permissions: 0o655
    content: |
      [Unit]
      Description=Nomad
      Documentation=https://nomadproject.io/docs/

      [Service]
      KillMode=process
      KillSignal=SIGINT
      ExecStart=/usr/local/bin/nomad agent --config /etc/nomad.d/ ${ nomad_server ? "-server" : "" } ${ nomad_client ? "-client" : "" }
      ExecReload=/bin/kill -HUP $MAINPID
      LimitNOFILE=65536
      Restart=always

      [Install]
      WantedBy=multi-user.target

  - path: /etc/sysctl.d/bridge.conf
    permissions: 0o655
    content: |
      net.bridge.bridge-nf-call-arptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

  - path: /opt/init/init.sh
    permissions: 0o755
    content: |
      sysctl -w vm.max_map_count=262144
      echo vm.max_map_count=262144 | tee -a /etc/sysctl.conf
      sysctl -w fs.file-max=65536
      echo fs.file-max=65536 | tee -a /etc/sysctl.conf

  - path: /opt/init/install-nomad.sh
    permissions: 0o755
    content: |
      curl https://releases.hashicorp.com/nomad/${nomad_version}/nomad_${nomad_version}_linux_amd64.zip -o /opt/init/nomad.zip
      unzip /opt/init/nomad.zip -d /opt/init/
      cp /opt/init/nomad /usr/local/bin/nomad
      chmod +x /usr/local/bin/nomad
      systemctl daemon-reload
      systemctl enable nomad
      systemctl start nomad

  - path: /opt/init/install-cni.sh
    permissions: 0o755
    content: |
      curl -L -o cni-plugins.tgz https://github.com/containernetworking/plugins/releases/download/v1.0.0/cni-plugins-linux-amd64-v1.0.0.tgz
      mkdir -p /opt/cni/bin
      tar -C /opt/cni/bin -xzf cni-plugins.tgz

runcmd:
  - /opt/init/init.sh
  - /opt/init/install-nomad.sh
  - /opt/init/install-cni.sh

cloud_final_modules:
  - [package_update_upgrade_install, once]
  - [scripts-user, once]
