#cloud-config

package_update: true
package_upgrade: true
packages:
  - curl
  - unzip

users:
- name: nomad
  gecos: Nomad User
  shell: /bin/bash
  groups: users,admin,wheel,lxd
  sudo: ALL=(ALL) NOPASSWD:ALL

write_files:
  - path: /etc/nomad.d/nomad.hcl
    owner: nomad:nomad
    permissions: 0o600
    defer: true
    content: |
      datacenter="${nomad_datacenter}"
      data_dir="/var/lib/nomad"
      client { 
       enabled = ${nomad_server?"false":"true"}
        server_join {
          retry_join = ["${join}"]
        }
        options { 
          docker.privileged.enabled = true 
          driver.aw_exec.enable = true
        }
      }
      server {
        enabled = ${nomad_client?"false":"true"}
        bootstrap_expect = ${nomad_server_count}
      }
  - path: /etc/systemd/system/nomad.service
    content: |
      [Unit]
      Description=Nomad
      Documentation=https://nomadproject.io/docs/

      [Service]
      KillMode=process
      KillSignal=SIGINT
      ExecStart=/usr/local/bin/nomad agent --config /etc/nomad.d/ -${server?"server":"client"}
      ExecReload=/bin/kill -HUP $MAINPID
      LimitNOFILE=65536
      Restart=always

      [Install]
      WantedBy=multi-user.target

runcmd:
  - mkdir -p /opt/init
  - curl https://releases.hashicorp.com/nomad/${nomad_version}/nomad_${nomad_version}_linux_amd64.zip -o /opt/init/nomad.zip
  - unzip /opt/init/nomad.zip -d /opt/init/
  - cp /opt/init/nomad /usr/local/bin/nomad
  - chmod +x /usr/local/bin/nomad
  - systemctl daemon-reload
  - systemctl enable nomad
  - systemctl start nomad
