#cloud-config

package_update: true
package_upgrade: true
packages:
  - curl
  - unzip

users:
- name: nomad
  gecos: Nomad User
  shell: /bin/bash
  groups: users,admin,wheel,lxd
  sudo: ALL=(ALL) NOPASSWD:ALL

write_files:
  - path: /etc/nomad.d/nomad.hcl
    owner: nomad:nomad
    permissions: 0o600
    defer: true
    content: ${nomad_config}
  - path: /etc/systemd/system/nomad.service
    content: ${nomad_systemd_service}
  - path: /opt/init/init.sh
    content: ${init_script}

runcmd:
  - /opt/init/init.sh
