name: Terraform Apply

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: GitHub checkout
        uses: actions/checkout@v4
      - name: Google Cloud authenticate
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/998902220107/locations/global/workloadIdentityPools/github-actions/providers/github
          service_account: github-actions@summer-sun-394510.iam.gserviceaccount.com
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2
      - name: Terraform init
        run: terraform init
      - name: Terraform apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
          TF_VAR_IAP_CLIENT_ID: ${{ secrets.IAP_CLIENT_ID }}
          TF_VAR_IAP_CLIENT_SECRET: ${{ secrets.IAP_CLIENT_SECRET }}
